### ISSUE TITLE
Width Specified twice for nav-submenu-list

### ISSUE THREAD

**Issue by cyface** [barryross/the-ascent#1]
https://github.com/barryross/the-ascent/blob/4258474c276e59d5bd2e61416b20f37105679dc5/nav.css#L562

Not sure which width is the correct one?

**Comment by barryross** [comment]
@cyface  Thank you...good catch!  I've removed the `width:auto;`

**Comment by cyface** [comment]
Great, thanks!

**Comment by barryross** [comment]
@cyface you're welcome!
