### ISSUE TITLE
Missing Comma?

### ISSUE THREAD

**Issue by cyface** [barryross/the-ascent#2]
https://github.com/barryross/the-ascent/blob/4258474c276e59d5bd2e61416b20f37105679dc5/nav.css#L582

Should there be a comma at the end of this line?

**Comment by barryross** [comment]
@cyface  I believe this is actually extraneous and have now removed it.

**Comment by cyface** [comment]
Great, thanks!

**Comment by barryross** [comment]
@cyface Welcome!
