### ISSUE TITLE
Keyboard Navigation

### ISSUE THREAD

**Issue by cyface** [barryross/the-ascent#3]
Hi! 
 I have this running on https://preview.www.fool.com/the-ascent/

 Working with the keyboard navigation, I was able to get multiple menus to open.  Also, I think we need to have the arrow keys work to move up and down the menus, and between them?

<img width="476" alt="screen shot 2018-12-26 at 8 59 03 am" src="https://user-images.githubusercontent.com/49695/50450673-9a90dd80-08ec-11e9-8a9d-b0cb213f45bc.png">

**Comment by barryross** [comment]
@cyface  Hey Tim...I've gone ahead and resolved the issue whereby multiple menus could be open at once when using the keyboard.  Currently, you are able to navigate through the menu items using `tab` and `shift+tab` which is the same functionality that appears on the following "Fly-out" menu example here: 

https://www.w3.org/WAI/tutorials/menus/flyout/#flyoutnavkbbtn

So, it seems that may be the standard way to allow for keyboard nav in terms of accessibility?

**Comment by cyface** [comment]
Sounds good, closing this one!

**Comment by barryross** [comment]
@cyface Great!
